

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Este comando aplica migraciones al iniciar y luego corre el servidor
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"